import Head from 'next/head'
import Navbar from '@/components/customInputs/AppBar'
import CommentPicker from '@/components/home/CommentPicker'
import { useEffect } from 'react'

export default function Home() {
  useEffect(() => {
    localStorage.clear();
  },[])
  return (
    <>
      <Head>
        <title>ViralKit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <CommentPicker />
      </main>
      
    </>
  )
}
