import Head from 'next/head'
// import { Inter } from 'next/font/google'
import Navbar from '@/components/AppBar/AppBar'
import CommentPicker from '@/components/CommentPicker/CommentPicker'
import { MainPageHeader } from '@/components/Header/Header'

// const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>ViralKit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        {/* <MainPageHeader/> */}
        <CommentPicker />
      </main>
      
    </>
  )
}
